version: 2
jobs:
  build:
    docker:
      - image: circleci/node:7.10
    working_directory: ~/repo
    steps:
      - checkout
      - run: echo "noop"
  deploy:
    machine:
      enabled: true
    working_directory: ~/repo
    steps:
      - add_ssh_keys:
          fingerprints:
            - "c1:03:23:fe:18:de:55:2c:80:49:10:ed:58:73:cb:00"
      - checkout
      - run:
          name: Deploy master to Dokku
          command: git push remote dokku@138.197.132.181
workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - deploy
